[package]
name = "signalk"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "A library to parse signalk maritime data"
# homepage = "https://github.com/balp/signalk/settings/pages"
# documentation = "https://docs.rs/bitflags"
repository = "https://github.com/balp/signalk/"
readme = "README.md"

keywords = ["signalk", "opendata", "marine"]
categories = ["data-structures"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
exclude = [
    ".idea/*",
    ".github/*",
    "docs/*",
]
[dependencies]
derive_more = "0.99.17"
bytes = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"