name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get rust tool chain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    - name: Rust Cache # cache the rust build artefacts
      uses: Swatinem/rust-cache@v2
    - name: Show Limits
      run: ulimit -s
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: env RUST_MIN_STACK=4194304 cargo test --verbose
    - name: cargo clippy warning
      run: cargo clippy --no-deps
    - name: cargo fmt check
      run: cargo fmt --check
    - name: Make API docs
      run: | 
        cargo doc --verbose
        mkdir -p docs/_static
        mv target/doc docs/_static/rust_api

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
         python-version: "3.11"
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         python -m pip install sphinx myst-parser sphinxcontrib-kroki groundwork-sphinx-theme
    - name: Build User Docs
      run: |
        cp README.md docs/
        sphinx-build -b html docs out/html
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: out/html
        force_orphan: true